version: '3.8'

services:
  web:
    image: pavlovsvpavel
    build: .
    command: gunicorn house_manager.wsgi:application --bind=0.0.0.0:8000
    env_file:
      - envs/.env.prod
    volumes:
      - /app/staticfiles:/app/static
    ports:
      - "8000:8000"
    platform: linux/amd64
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - envs/.env.prod
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - ./static_files:/app/static
      - ./mediafiles:/app/mediafiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - web

