version: '3.8'

services:
  web:
    image: ppavlovp/house_manager:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    volumes:
      - ./staticfiles:/tmp/house_manager/static_files
      - ./mediafiles:/tmp/house_manager/mediafiles
      - ./locale:/tmp/house_manager/locale
    platform: linux/amd64
    command: gunicorn house_manager.wsgi:application --bind=0.0.0.0:8000
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - "81:80"
    volumes:
      - ./staticfiles:/home/app/web/static_files
      - ./mediafiles:/home/app/web/mediafiles
      - ./locale:/home/app/web/locale
      - ./nginx/dev/conf.d:/etc/nginx/conf.d
      - ./nginx/dev/logs:/var/log/nginx
    depends_on:
      - web