services:
  web:
    container_name: house_manager_app_web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env.local
    environment:
      - GUNICORN_WORKERS=2
    volumes:
      - ./static_files:/var/www/house_manager/static_files/
      - ./mediafiles:/var/www/house_manager/mediafiles/
      - ./locale:/var/www/house_manager/locale/
    platform: linux/amd64
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    depends_on:
      - postgres

  postgres:
    container_name: house_manager_app_postgres
    image: postgres:17
    restart: always
    ports:
      - "5434:5432"
    env_file:
      - ./envs/.env.local
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 384M

  nginx:
    container_name: house_manager_app_nginx
    image: nginx
    restart: always
    ports:
      - "127.0.0.1:81:80"
    volumes:
      - ./nginx/local/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/local/custom_pages/50x.html:/usr/share/nginx/html/50x.html:ro
      - ./nginx/local/conf.d:/etc/nginx/conf.d/:ro
      - ./nginx/local/logs:/var/log/nginx
      - ./static_files:/var/www/house_manager/static_files/:ro
      - ./mediafiles:/var/www/house_manager/mediafiles/:ro
      - ./locale:/var/www/house_manager/locale/:ro
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 100M
    depends_on:
      - web