services:
  web:
    image: ppavlovp/house_manager:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./terraform/.env.aws
    volumes:
      - ./staticfiles:/tmp/house_manager/static_files
      - ./mediafiles:/tmp/house_manager/mediafiles
      - ./locale:/tmp/house_manager/locale
    platform: linux/amd64
    command: gunicorn house_manager.wsgi:application --bind=0.0.0.0:8000
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./terraform/.env.aws
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./staticfiles:/home/app/web/static_files
      - ./mediafiles:/home/app/web/mediafiles
      - ./locale:/home/app/web/locale
      - ./nginx/aws/conf.d:/etc/nginx/conf.d
      - ./nginx/aws/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web



