services:
  web:
    container_name: house_manager_app_web_prod
    image: house_manager:prod
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env.prod
    volumes:
      - ./staticfiles:/tmp/house_manager/static_files
      - ./mediafiles:/tmp/house_manager/mediafiles
      - ./locale:/tmp/house_manager/locale
    platform: linux/amd64
    command: bash -c "gunicorn house_manager.wsgi:application --bind=0.0.0.0:8000 --workers=$((2 * $(nproc) + 1)) --timeout=120"
    depends_on:
      - postgres
  postgres:
    container_name: house_manager_app_postgres_prod
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./envs/.env.prod
    volumes:
      - ./postgresql_prod:/var/lib/postgresql/data
  nginx:
    container_name: house_manager_app_nginx_prod
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/home/app/web/static_files
      - ./mediafiles:/home/app/web/mediafiles
      - ./locale:/home/app/web/locale
      - ./nginx/prod/conf.d:/etc/nginx/conf.d
      - ./nginx/prod/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web



