version: '3.8'

services:
  web:
    image: ppavlovp/house_manager
    build: ./house_manager
    ports:
      - "8000:8000"
    env_file:
      - envs/.env
    volumes:
      - ./staticfiles:/tmp/house_manager/static_files
    platform: linux/amd64
    command: gunicorn house_manager.wsgi:application --bind=0.0.0.0:8000
    links:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - envs/.env
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./staticfiles:/home/app/web/static_files
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - web



