services:
  web:
    container_name: house_manager_app_web
    image: house_manager:prod
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env.prod
    volumes:
      - ./staticfiles:/tmp/house_manager/static_files
      - ./mediafiles:/tmp/house_manager/mediafiles
      - ./locale:/tmp/house_manager/locale
    platform: linux/amd64
    depends_on:
      - postgres

  postgres:
    container_name: house_manager_app_postgres
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./envs/.env.prod
    volumes:
      - ./postgresql_prod:/var/lib/postgresql/data

  nginx:
    container_name: house_manager_app_nginx
    image: nginx
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/prod/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/prod/conf.d:/etc/nginx/conf.d/:ro
      - ./nginx/prod/logs:/var/log/nginx
      - ./staticfiles:/home/app/web/static_files/:ro
      - ./mediafiles:/home/app/web/mediafiles/:ro
      - ./locale:/home/app/web/locale/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web



