services:
  web:
    container_name: house_manager_app_web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_BUILDKIT: 1
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./envs/.env.local
    environment:
      - GUNICORN_WORKERS=10
      - GUNICORN_RELOAD=true
    volumes:
      - ./staticfiles:/tmp/house_manager/static_files/
      - ./mediafiles:/tmp/house_manager/mediafiles/
      - ./locale:/tmp/house_manager/locale
    platform: linux/amd64
    depends_on:
      - postgres

  postgres:
    container_name: house_manager_app_postgres
    image: postgres:17
    restart: always
    ports:
      - "5434:5432"
    env_file:
      - ./envs/.env.local
    volumes:
      - ./postgres_db:/var/lib/postgresql/data

  nginx:
    container_name: house_manager_app_nginx
    image: nginx
    restart: on-failure
    ports:
      - "127.0.0.1:81:80"
    volumes:
      - ./nginx/local/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/local/conf.d:/etc/nginx/conf.d/:ro
      - ./nginx/local/logs:/var/log/nginx
      - ./staticfiles:/tmp/house_manager/static_files/:ro
      - ./mediafiles:/tmp/house_manager/mediafiles/:ro
      - ./locale:/tmp/house_manager/locale/:ro
    depends_on:
      - web