services:
  web:
    container_name: house_manager_app_web_dev
    image: house_manager:dev
    build:
      context: .
      dockerfile: Dockerfile_dev
      args:
        DOCKER_BUILDKIT: 1
    restart: always
    ports:
      - "8001:8000"
    env_file:
      - ./envs/.env.dev
    volumes:
      - ./staticfiles:/tmp/house_manager/dev/static_files
      - ./mediafiles:/tmp/house_manager/dev/mediafiles
      - ./locale:/tmp/house_manager/dev/locale
    platform: linux/amd64
    command: gunicorn house_manager.wsgi:application --bind=0.0.0.0:8000
    depends_on:
      - postgres
  postgres:
    container_name: house_manager_app_postgres_dev
    image: postgres_dev
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - ./envs/.env.dev
    volumes:
      - ./postgresql_dev:/var/lib/postgresql/data
  nginx:
    container_name: house_manager_app_nginx_dev
    image: nginx
    restart: always
    ports:
      - "88:80"
      - "444:443"
    volumes:
      - ./staticfiles:/home/app/web/dev/static_files
      - ./mediafiles:/home/app/web/dev/mediafiles
      - ./locale:/home/app/web/dev/locale
      - ./nginx/dev/conf.d:/etc/nginx/conf.d
      - ./nginx/dev/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web