# Generated by Django 5.0.2 on 2024-03-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmonthlybill',
            options={'ordering': ('year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='clientmonthlybill',
            unique_together={('year', 'month')},
        ),
    ]
