# Generated by Django 5.0.2 on 2024-03-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmonthlybill',
            options={'ordering': ('-year', 'month')},
        ),
    ]
