# Generated by Django 5.0.2 on 2024-03-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_bills', '0002_alter_clientmonthlybill_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmonthlybill',
            options={'ordering': ['year', 'month']},
        ),
    ]
