# Generated by Django 5.1.2 on 2024-11-06 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_bills', '0002_clientmonthlybill_signature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmonthlybill',
            old_name='fee_manager_and_cashier',
            new_name='fee_manager',
        ),
    ]
