# Generated by Django 5.1.2 on 2024-11-06 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_bills', '0003_rename_clientmonthlybill_fee_manager_and_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmonthlybill',
            name='fee_cashier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Please enter a value greater than zero')], verbose_name='Cashier fee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientmonthlybill',
            name='fee_manager',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Please enter a value greater than zero')], verbose_name='Manager fee'),
        ),
    ]
