# Generated by Django 5.0.2 on 2024-03-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_bills', '0003_alter_clientmonthlybill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmonthlybill',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='clientmonthlybill',
            unique_together=set(),
        ),
    ]
