# Generated by Django 5.1.2 on 2024-11-06 09:16

import django.core.validators
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_bills', '0006_remove_clientmonthlybill_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmonthlybill',
            name='total_amount',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('electricity_common'), '+', models.F('electricity_lift')), '+', models.F('internet')), '+', models.F('maintenance_lift')), '+', models.F('fee_cleaner')), '+', models.F('fee_manager')), '+', models.F('fee_cashier')), '+', models.F('repairs')), '+', models.F('others')), output_field=models.DecimalField(decimal_places=2, max_digits=10), validators=[django.core.validators.MinValueValidator(0, message='Please enter a value greater than zero')], verbose_name='Total BGN'),
        ),
    ]
