# Generated by Django 5.1.6 on 2025-03-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_bills', '0008_remove_clientmonthlybill_total_amount_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmonthlybill',
            name='year',
            field=models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=4, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='clientotherbill',
            name='year',
            field=models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=4, verbose_name='Year'),
        ),
    ]
