# Generated by Django 5.1.7 on 2025-03-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_bills', '0009_alter_clientmonthlybill_year_and_more'),
        ('client_bills', '0009_clientmonthlybill_amount_old_debts_and_more'),
    ]

    operations = [
    ]
