# Generated by Django 5.1.7 on 2025-03-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_bills', '0010_merge_20250321_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmonthlybill',
            name='amount_old_debts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unpaid bills, BGN'),
        ),
        migrations.AlterField(
            model_name='clientmonthlybill',
            name='signature',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='clientotherbill',
            name='signature',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
