# Generated by Django 5.1 on 2024-08-12 19:30

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseOtherBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=9, verbose_name='Month')),
                ('year', models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4, verbose_name='Year')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Please enter a value greater than zero')], verbose_name='Total BGN')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('type_of_bill', models.CharField(choices=[('Single bill', 'Single bill'), ('Bill for all clients', 'Bill for all clients')], max_length=20, verbose_name='Type of bill')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_other_bills', to='houses.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('is_paid', '-year', 'month'),
            },
        ),
        migrations.CreateModel(
            name='HouseMonthlyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=9, verbose_name='Month')),
                ('year', models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4, verbose_name='Year')),
                ('electricity_common', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Please enter a value greater than zero')], verbose_name='Electricity common')),
                ('electricity_lift', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Please enter a value greater than zero')], verbose_name='Electricity lift')),
                ('internet', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Please enter a value greater than zero')], verbose_name='Internet')),
                ('maintenance_lift', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Please enter a value greater than zero')], verbose_name='Lift maintenance')),
                ('fee_cleaner', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Please enter a value greater than zero')], verbose_name='Cleaner fee')),
                ('fee_manager_and_cashier', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Please enter a value greater than zero')], verbose_name='Manager/Cashier fee')),
                ('repairs', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Please enter a value greater than zero')], verbose_name='Repairs fund')),
                ('others', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Please enter a value greater than zero')], verbose_name='Other expenses')),
                ('total_amount', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('electricity_common'), '+', models.F('electricity_lift')), '+', models.F('internet')), '+', models.F('maintenance_lift')), '+', models.F('fee_cleaner')), '+', models.F('fee_manager_and_cashier')), '+', models.F('repairs')), '+', models.F('others')), output_field=models.DecimalField(decimal_places=2, max_digits=10), validators=[django.core.validators.MinValueValidator(0, message='Please enter a value greater than zero')], verbose_name='Total BGN')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_monthly_bills', to='houses.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('is_paid', '-year', 'month'),
                'unique_together': {('year', 'month', 'house')},
            },
        ),
    ]
