# Generated by Django 5.0.2 on 2024-03-20 13:15

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseMonthlyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('electricity_common', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electricity_lift', models.DecimalField(decimal_places=2, max_digits=10)),
                ('internet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance_lift', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_cleaner', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_manager_and_cashier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repairs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('others', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('electricity_common'), '+', models.F('electricity_lift')), '+', models.F('internet')), '+', models.F('maintenance_lift')), '+', models.F('fee_cleaner')), '+', models.F('fee_manager_and_cashier')), '+', models.F('repairs')), '+', models.F('others')), output_field=models.DecimalField(decimal_places=2, max_digits=10))),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_monthly_bills', to='houses.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'month'],
                'unique_together': {('year', 'month', 'house')},
            },
        ),
        migrations.CreateModel(
            name='HouseOtherBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=10)),
                ('year', models.CharField(max_length=4)),
                ('comment', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_other_bills', to='houses.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'month'],
                'unique_together': {('year', 'month', 'house')},
            },
        ),
    ]
