# Generated by Django 5.0.2 on 2024-04-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='houseotherbill',
            unique_together=set(),
        ),
    ]
