# Generated by Django 5.0.2 on 2024-03-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houseotherbill',
            options={'ordering': ('is_paid', '-year', 'month')},
        ),
    ]
