# Generated by Django 5.0.2 on 2024-02-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemonthlybill',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10),
        ),
        migrations.AlterField(
            model_name='housemonthlybill',
            name='year',
            field=models.CharField(choices=[], max_length=4),
        ),
    ]
