# Generated by Django 5.0.2 on 2024-03-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemonthlybill',
            name='month',
            field=models.CharField(choices=[('01', 'January'), ('02', 'February'), ('03', 'March'), ('04', 'April'), ('05', 'May'), ('06', 'June'), ('07', 'July'), ('08', 'August'), ('09', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], max_length=9),
        ),
    ]
