# Generated by Django 5.0.2 on 2024-02-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_bills', '0002_alter_housemonthlybill_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemonthlybill',
            name='year',
            field=models.CharField(choices=[('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027')], max_length=4),
        ),
    ]
