# Generated by Django 5.0.2 on 2024-03-16 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_bills', '0002_housemonthlybill_money_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemonthlybill',
            name='money_balance',
        ),
    ]
