# Generated by Django 5.1.2 on 2024-11-05 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_bills', '0002_housemonthlybill_signature_houseotherbill_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemonthlybill',
            name='fee_cashier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Please enter a value greater than zero')], verbose_name='Cashier fee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housemonthlybill',
            name='total_amount_temp',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='housemonthlybill',
            name='fee_manager_and_cashier',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Please enter a value greater than zero')], verbose_name='Manager fee'),
        ),
    ]
