# Generated by Django 5.0.2 on 2024-03-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_bills', '0003_remove_housemonthlybill_money_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemonthlybill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
