# Generated by Django 5.0.2 on 2024-03-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_bills', '0003_alter_housemonthlybill_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housemonthlybill',
            options={'ordering': ('year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='housemonthlybill',
            unique_together={('year', 'month')},
        ),
    ]
