# Generated by Django 5.0.2 on 2024-03-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_bills', '0004_alter_housemonthlybill_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housemonthlybill',
            options={'ordering': ['year', 'month']},
        ),
    ]
