# Generated by Django 5.0.2 on 2024-03-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_bills', '0004_housemonthlybill_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemonthlybill',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
    ]
