# Generated by Django 5.1.2 on 2024-11-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_bills', '0007_housemonthlybill_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemonthlybill',
            name='total_amount_temp',
        ),
    ]
