# Generated by Django 5.1.7 on 2025-03-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_bills', '0009_alter_housemonthlybill_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemonthlybill',
            name='signature',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='houseotherbill',
            name='signature',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
