# Generated by Django 6.0 on 2026-01-03 09:45

import django.core.validators
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_bills', '0010_alter_housemonthlybill_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemonthlybill',
            name='total_amount',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('electricity_common'), '+', models.F('electricity_lift')), '+', models.F('internet')), '+', models.F('maintenance_lift')), '+', models.F('fee_cleaner')), '+', models.F('fee_manager')), '+', models.F('fee_cashier')), '+', models.F('repairs')), '+', models.F('others')), output_field=models.DecimalField(decimal_places=2, max_digits=10), validators=[django.core.validators.MinValueValidator(0, message='Please enter a value greater than zero')], verbose_name='Total EUR'),
        ),
        migrations.AlterField(
            model_name='housemonthlybill',
            name='year',
            field=models.CharField(choices=[('2025', '2025'), ('2026', '2026'), ('2027', '2027')], max_length=4, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='houseotherbill',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='Please enter a value greater than zero')], verbose_name='Total EUR'),
        ),
        migrations.AlterField(
            model_name='houseotherbill',
            name='year',
            field=models.CharField(choices=[('2025', '2025'), ('2026', '2026'), ('2027', '2027')], max_length=4, verbose_name='Year'),
        ),
    ]
