# Generated by Django 5.0.2 on 2024-02-29 07:47

import house_manager.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists'}, max_length=30, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, validators=[house_manager.common.validators.validate_char_field])),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, validators=[house_manager.common.validators.validate_char_field])),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[house_manager.common.validators.validate_phone_number])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
