# Generated by Django 5.0.2 on 2024-04-08 20:02

import cloudinary.models
import house_manager.accounts.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[house_manager.accounts.validators.validate_profile_picture_size], verbose_name='Profile picture'),
        ),
    ]
