# Generated by Django 5.1.2 on 2024-12-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemanageruser',
            name='has_set_password',
            field=models.BooleanField(default=False),
        ),
    ]
