# Generated by Django 5.0.2 on 2024-03-24 20:09

import django.db.models.deletion
import house_manager.common.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('town', models.CharField(max_length=20, validators=[house_manager.common.validators.validate_char_field], verbose_name='Town')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('building_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Building number')),
                ('entrance', models.CharField(max_length=2, verbose_name='Entrance')),
                ('money_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
