# Generated by Django 5.0.2 on 2024-02-29 07:47

import django.db.models.deletion
import house_manager.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('town', models.CharField(max_length=20, validators=[house_manager.common.validators.validate_char_field])),
                ('address', models.CharField(max_length=100)),
                ('building_number', models.PositiveIntegerField(blank=True, null=True)),
                ('entrance', models.CharField(max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='accounts.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
