# Generated by Django 5.0.2 on 2024-03-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='entrance',
            field=models.CharField(max_length=2),
        ),
    ]
