# Generated by Django 6.0 on 2026-01-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_housecalculationsoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='fixed_monthly_taxes',
            field=models.BooleanField(default=False, verbose_name='Fixed monthly taxes'),
        ),
    ]
