# Generated by Django 5.0.2 on 2024-03-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_house_entrance'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='money_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
