# Generated by Django 5.0.2 on 2024-03-19 13:23

import django.db.models.deletion
import house_manager.common.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('family_name', models.CharField(max_length=30, validators=[house_manager.common.validators.validate_char_field])),
                ('floor', models.PositiveIntegerField()),
                ('apartment', models.PositiveIntegerField()),
                ('number_of_people', models.PositiveIntegerField()),
                ('is_using_lift', models.BooleanField(default=True)),
                ('is_occupied', models.BooleanField(default=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='houses.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['house', 'apartment'],
                'unique_together': {('apartment', 'house')},
            },
        ),
    ]
