# Generated by Django 5.1 on 2024-09-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_inhabitable',
            field=models.BooleanField(default=True, verbose_name='Inhabitable'),
        ),
    ]
