# Generated by Django 5.0.2 on 2024-03-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='fixed_fee',
        ),
    ]
