# Generated by Django 5.2.3 on 2025-07-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_is_inhabitable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_using_lift',
            field=models.BooleanField(default=True, verbose_name='Lift'),
        ),
    ]
