# Generated by Django 6.0.3 on 2026-04-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_is_using_lift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='apartment',
            field=models.CharField(max_length=10, verbose_name='Apartment'),
        ),
    ]
