# Generated by Django 6.0.3 on 2026-04-05 08:09

import house_manager.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_apartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='family_name',
            field=models.CharField(max_length=60, validators=[house_manager.common.validators.validate_char_field], verbose_name='Family Name'),
        ),
    ]
