name: Update Django app to development

on:
  workflow_dispatch:

jobs:
  update_django_app:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
                cd /home/ubuntu/app/House_Manager_App
                sudo git pull
                sudo docker-compose -f docker-compose.dev.yml -p development up -d --build
                sudo docker-compose -f docker-compose.dev.yml -p development exec -T web python manage.py migrate
                sudo docker-compose -f docker-compose.dev.yml -p development exec -T web python manage.py collectstatic --noinput
                sudo docker-compose -f docker-compose.dev.yml -p development exec -T web python manage.py makemessages -l bg
                sudo docker-compose -f docker-compose.dev.yml -p development exec -T web python manage.py compilemessages
                docker restart $(docker ps -q --filter "name=dev")