name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.3.0"

      - name: Terraform Init
        run: cd terraform && terraform init

      - name: Terraform Format
        run: cd terraform && terraform fmt -check

      - name: Check and Import Key Pair if Exists
        id: check_key
        run: |
          cd terraform
          chmod +x ./check_keypair.sh
          ./check_keypair.sh

      - name: Terraform Import Key Pair if Exists
        if: env.exists == 'true'
        run: |
          cd terraform
          terraform import aws_key_pair.akp house-manager-terraform-key

      - name: Terraform Plan
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

        run: cd terraform && terraform plan -var-file="values.tfvars" -input=false

      - name: Terraform Apply
        if: env.exists != 'true'  # Apply if the key pair does not exist
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: cd terraform && terraform apply -var-file="values.tfvars" -auto-approve -input=false

