name: 'Terraform'

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    - name: Terraform Init
      run: cd terraform && terraform init

    - name: Terraform Format
      run: cd terraform && terraform fmt -check

    - name: Terraform Plan
      run: cd terraform && terraform plan -input=false

    - name: Terraform Apply
      env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GH_PAT: ${{ secrets.GH_PAT }}

      run: cd terraform && terraform apply -var-file="values.tfvars" -auto-approve -input=false

