name: Deploy to AWS with Terraform

on:
  workflow_dispatch: on
#  push:
#    branches:
#      - main
#  pull_request:
#    branches:
#      - main

jobs:
  create_key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create SSH private key file
        run: |
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > house_manager_new_key.pem
          chmod 600 house_manager_new_key.pem

      - name: Upload SSH Key as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssh_private_key
          path: house_manager_new_key.pem

  create_ec2_instance_and_deploy_the_app:
    runs-on: ubuntu-latest
    needs: create_key
    outputs:
      public_dns: ${{ steps.get_public_dns.outputs.public_dns }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.3.0

      - name: Set Up AWS CLI
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION

      - name: Download SSH Key Artifact
        uses: actions/download-artifact@v4
        with:
          name: ssh_private_key
          path: ./

      - name: Fix Permissions on Private Key
        run: chmod 600 ./house_manager_new_key.pem

      - name: Terraform Init
        run: cd terraform && terraform init

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -var-file="values.tfvars" -input=false

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -var-file="values.tfvars" -auto-approve -input=false

      - name: Get Public DNS from Terraform Outputs
        id: get_public_dns
        run: |
          cd terraform
          echo "PUBLIC_DNS=$(terraform output -raw public_dns)" >> "$GITHUB_ENV"

      - name: Copy Scripts to EC2
        run: |
          scp -i ./house_manager_new_key.pem -o StrictHostKeyChecking=no -r terraform/scripts/* ${{ secrets.EC2_USER }}@$PUBLIC_DNS:/home/ubuntu/app/scripts/

      - name: Download .env from S3
        run: |
          aws s3 cp s3://storage-for-env-files/.env/.env.aws .env.aws || { echo "Error: $?" ; exit 1; }

      - name: Copy.env to EC2
        run: |
          scp -i ./house_manager_new_key.pem -o StrictHostKeyChecking=no .env.aws ${{ secrets.EC2_USER }}@$PUBLIC_DNS:/home/ubuntu/app/envs/

      - name: Run commands for setting up Docker containers
        run: |
          ssh -i ./house_manager_new_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@$PUBLIC_DNS "bash /home/ubuntu/app/scripts/setup.sh"

      - name: Run Django management commands inside the web container
        run: |
          ssh -i ./house_manager_new_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@$PUBLIC_DNS "bash /home/ubuntu/app/scripts/setup-web-container.sh"